- name: Download client binary
  get_url:
    url: '{{ restic_rest_url }}'
    dest: '/tmp/'
  register: get_url_restic

- name: Decompress the binary
  shell: "gzip -dc {{ get_url_restic.dest }} > {{ restic_install_path }}/{{ restic_rest_binary }}-{{ restic_rest_v }}"
  args:
    creates: '{{ restic_install_path }}/{{ restic_rest_binary }}-{{ restic_rest_v }}'
  when: not restic_use_custom_binary

