---

- name: set internal variable platform-suffix
  set_fact:
    _platform_suffix: 'linux-amd64'
  when: ansible_userspace_bits == '64'

- name: set internal variable platform-suffix
  set_fact:
    _platform_suffix: 'linux-386'
  when: ansible_userspace_bits == '32'

- import_tasks: install_binary.yml
  when: restic_use_custom_binary

- import_tasks: install_url.yml
  when: not restic_use_custom_binary

- name: Ensure binary permissions are correct
  file:
    path: '{{ restic_install_path }}/{{ restic_rest_binary }}-{{ restic_rest_v }}'
    mode: '0755'
    owner: 'root'
    group: 'root'
  when: not ansible_check_mode

- name: Create symlink
  file:
    path: '{{ restic_install_path }}/{{ restic_rest_binary }}'
    src: '{{ restic_install_path }}/{{ restic_rest_binary }}-{{ restic_rest_v }}'
    state: 'link'
    mode: '0755'
    owner: 'root'
    group: 'root'
  when: not ansible_check_mode
