---
- name: Converge
  hosts: all
  become: true
  roles:
    - role: ansible-restic-rest
      vars:
        restic_use_custom_binary: true
        restic_rest_repos:
          - path: '/var/backups/projecta'
            listen: ':8001'
            args: '--append-only --private-repos'
